name: Tag

on:
  push:
    branches: [main]

jobs:
  build:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: paulhatch/semantic-version@v4.0.2
        id: semver
        name: Calculate version
        with:
          tag_prefix: "v"
          format: "${major}.${minor}.${patch}"

      - name: Add git tags
        env:
          MAJOR: ${{ steps.semver.outputs.major }}
          MINOR: ${{ steps.semver.outputs.minor }}
          VERSION: ${{ steps.semver.outputs.version }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a -m "Adding tags for release ${VERSION}" "v${VERSION}"
          if [ "${MAJOR}" != "0" ]; then
            git tag -a -m "Adding tags for release ${VERSION}" "v${MAJOR}"
            git tag -a -m "Adding tags for release ${VERSION}" "v${MAJOR}.${MINOR}"
          fi
          git push --follow-tags
        shell: bash
